package command_runner

import (
	"context"

	"github.com/Artenso/command-runner/internal/model"
	desc "github.com/Artenso/command-runner/pkg/command_runner"
)

// ICommandRunnerService is the interface of the service layer
type ICommandRunnerService interface {
	AddCommand(_ context.Context, command string) (int64, error)
	GetCommand(_ context.Context, id int64) (*model.Command, error)
	ListCommand(_ context.Context, limit, offset int64) ([]*model.Command, error)
	StopCommand(_ context.Context, id int64) error
}

// gRPC autogenerated interface implementation
type Implementation struct {
	desc.UnimplementedCommandRunnerServer

	commandRunnerSrv ICommandRunnerService
}

// NewCommandRunner creates new CommandRunner object
func NewCommandRunner(commandRunnerSrv ICommandRunnerService) *Implementation {
	return &Implementation{
		commandRunnerSrv: commandRunnerSrv,
	}
}
